version: "3.8"

services:
  fuel-hunter-mongo:
    image: mongo:latest
    container_name: fuel-hunter-mongo

  fuel-hunter:
    container_name: fuel-hunter
    ports:
      - 50051:50051
    environment:
      - DB_HOST=fuel-hunter-mongo
    depends_on:
      - fuel-hunter-mongo
    links:
      - fuel-hunter-mongo

  fuel-hunter-envoy:
    image: envoyproxy/envoy:v1.15-latest
    container_name: fuel-hunter-envoy
    ports:
    - 9901:9901
    - 8000:8000