version: "3.8"

services:
  fuel-hunter-mongo:
    env_file:
      - "/var/www/fuel_hunter/config/.env.prod"
    volumes:
      - "/.mongo/data:/data/db"

  fuel-hunter:
    env_file:
      - "/var/www/fuel_hunter/config/.env.prod"
    build:
      context: ./
      dockerfile: ./Dockerfile

  fuel-hunter-envoy:
    volumes:
    - "/var/www/fuel_hunter/config/descriptor_set.desc:/data/descriptor_set.desc"
    - "/var/www/fuel_hunter/config/config.linux.yml:/etc/envoy/envoy.yaml:ro"